---
- name: Check if {{ zenlist_old_path }} exists.
  stat: path={{ zenlist_old_path }} 
  register: old_zenlist_exist

- name: Check if {{ zenlist_new_path }} exists.
  stat: path={{ zenlist_new_path }} 
  register: new_zenlist_exist  

- name: Update Old Zen List
  shell: |
    sed -i {{ regex }} {{ zenlist_old_path }} 
    mv {{ zenlist_old_path }} {{ zenlist_new_path}}
  become: true
  when: old_zenlist_exist.stat.exists == True 

- name: Update New Zen List
  shell: sed -i {{ regex }} {{ zenlist_new_path }} 
  become: true
  when: new_zenlist_exist.stat.exists == True 

- name: Update Apt Cache and confirm repo update
  apt: update_cache=yes force_apt_get=yes

- name: Remove current apt zen lib
  shell: rm -r /var/lib/apt/lists/* 
  become: true

- name: Update apt cache and install zen, install new zen daemon if available
  apt:
    name=zen
    state=latest
    update_cache=yes
    force_apt_get=yes

- name: Download the required parameters for Zend
  command: zen-fetch-params
  become: true

- name: Stop zend after the upgrade has completed
  command: systemctl stop zend
  become: true
  
- name: Show zend version, expect 2.0.22
  command: zend --version
  register: zend_version

- debug: msg='{{ zend_version.stdout_lines }}'

- name: Start Zend 
  command: systemctl start zend
  become: true
  
- name: Restart Zentracker 
  command: systemctl restart zentracker  
  become: true